#!/bin/bash

while true
do
echo "----------------------------"
echo " SIMPLE CALCULATOR"
echo "----------------------------"
echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Division"
echo "5. Exit"
echo "----------------------------"

echo -n "Enter your choice [1-5]: "
read choice

case $choice in

1)
echo "Enter two numbers:"
read a b
result=$((a + b))
echo "Result = $result"
;;

2)
echo "Enter two numbers:"
read a b
result=$((a - b))
echo "Result = $result"
;;

3)
echo "Enter two numbers:"
read a b
result=$((a * b))
echo "Result = $result"
;;

4)
echo "Enter two numbers:"
read a b
if [ $b -eq 0 ]; then
    echo "Division by zero not allowed"
else
    result=$((a / b))
    echo "Result = $result"
fi
;;

5)
echo "Exiting Calculator..."
exit
;;

*)
echo "Invalid choice"
;;

esac

done
